opensrp/opensrp-client-giz-malawi

opensrp-giz-malawi/src/main/assets/json.form/child_enrollment.json

Child Registration json form

---

opensrp-giz-malawi/src/main/assets/json.form/child_enrollment.json

Changes include:
-Addition of village field
-Removal of unnecessary asterix
-Change of some hints text

Registration form

---

opensrp-giz-malawi/src/main/assets/json.form/child_enrollment.json
opensrp-giz-malawi/src/main/java/org/smartregister/giz/application/GizMalawiApplication.java
opensrp-giz-malawi/src/main/java/org/smartregister/giz/repository/GizMalawiRepository.java
opensrp-giz-malawi/src/main/java/org/smartregister/giz/util/GizConstants.java

Fx mother nrc lookup max date

---

opensrp-giz-malawi/src/main/assets/ec_client_fields.json
opensrp-giz-malawi/src/main/assets/json.form/child_enrollment.json
opensrp-giz-malawi/src/main/java/org/smartregister/giz/application/GizMalawiApplication.java
opensrp-giz-malawi/src/main/java/org/smartregister/giz/repository/GizMalawiRepository.java
opensrp-giz-malawi/src/main/java/org/smartregister/giz/util/GizConstants.java

1. Mother nrc number lookup
2. Addition of Out Of Catchment Event Type which was added in the latest build of opensrp-child
3. Added migration from the latest build of opensrp-immunization (it adds a service groups column)  
4. Made a fix of datepicker from native-forms so that the default value of date_picker should only reflect on the dialog....so for this repo added the default value.
5. Addition of ec_clients fields (mother_first_name,mother_last_name) that @ekigamba was working on.
Links to related PR
https://github.com/OpenSRP/opensrp-client-native-form/pull/261
https://github.com/OpenSRP/opensrp-client-child/pull/54

Addtion of column change ec clients field

---

opensrp-giz-malawi/src/main/assets/json.form/child_enrollment.json

#53 
1 Made mother id field alphanumeric
2. Fx mothers first name and mother last name take alphabet only

mother id alphanumeric

---

opensrp-giz-malawi/src/main/java/org/smartregister/giz/fragment/ChildRegisterFragment.java

Child register page record growth button

---

opensrp-giz-malawi/build.gradle
opensrp-giz-malawi/src/main/java/org/smartregister/giz/interactor/LoginInteractor.java

App sync does not refresh ui

---

opensrp-giz-malawi/src/main/assets/json.form/child_enrollment.json

fx child photo save

---

opensrp-giz-malawi/src/main/java/org/smartregister/giz/sync/GizMalawiProcessorForJava.java

#78 
If vaccination event comes before birth registration save the child first

fx fts update on sync

---

opensrp-giz-malawi/src/main/java/org/smartregister/giz/view/NavigationMenu.java

fx sync progress not showing

---

opensrp-giz-malawi/src/main/assets/ec_client_fields.json
opensrp-giz-malawi/src/main/assets/json.form/opd_registration.json
opensrp-giz-malawi/src/main/java/org/smartregister/giz/interactor/OpdRegisterActivityInteractor.java

fix-event-sync

---

opensrp-giz-malawi/src/main/assets/ec_client_height.json
opensrp-giz-malawi/src/main/assets/ec_client_weight.json
opensrp-giz-malawi/src/main/assets/recurring_service_types.json
opensrp-giz-malawi/src/main/assets/vaccines.json

modified:   opensrp-giz-malawi/src/main/assets/ec_client_weight.json
modified:   opensrp-giz-malawi/src/main/assets/recurring_service_types.json
modified:   opensrp-giz-malawi/src/main/assets/vaccines.json

	modified:   opensrp-giz-malawi/src/main/assets/ec_client_height.json

---

opensrp-giz-malawi/src/main/assets/config/indicator-definitions.yml
opensrp-giz-malawi/src/main/res/values/strings.xml

Completed review of Child and ANC reports

Final report changes

---

opensrp-giz-malawi/src/main/assets/config/indicator-definitions.yml

Add pnc reports

---

opensrp-giz-malawi/src/main/assets/DataDictionaryReporting.csv

Adding PNC DHIS2 data elements

---

opensrp-giz-malawi/src/main/assets/DataDictionaryReporting.csv

Added missing elements
Corrected wrong elements

Updating Data Dictionary DHIS2 Reports

---

opensrp-giz-malawi/src/main/assets/DataDictionaryReporting.csv

CHD EPI Number Dewormed Female 2nd Dose 12-23M Outreach
CHD EPI Number Dewormed Male 2nd Dose 12-23M Outreach
CHD EPI Number Dewormed Female 2nd Dose 24-59M Outreach
CHD EPI Number Dewormed Male 2nd Dose 24-59M Outreach
CHD EPI Number Dewormed Female 2nd Dose 12-23M Static
CHD EPI Number Dewormed Male 2nd Dose 12-23M Static
CHD EPI Number Dewormed Female 2nd Dose 24-59M Static
CHD EPI Number Dewormed Male 2nd Dose 24-59M Static

Update of dhis2 ids

---

opensrp-giz-malawi/build.gradle
opensrp-giz-malawi/src/main/java/org/smartregister/giz/fragment/FilterReportFragment.java
opensrp-giz-malawi/src/main/java/org/smartregister/giz/repository/GizMalawiRepository.java
opensrp-giz-malawi/src/test/java/org/smartregister/giz/activity/ChildRegisterActivityTest.java
opensrp-giz-malawi/src/test/java/org/smartregister/giz/activity/LoginActivityTest.java
opensrp-giz-malawi/src/test/java/org/smartregister/giz/activity/ReportRegisterActivityTest.java

Resets the Calendar date onResume

Date fixed

---

opensrp-giz-malawi/build.gradle
opensrp-giz-malawi/src/main/assets/config/indicator-definitions.yml
opensrp-giz-malawi/src/main/assets/json.form/opd_diagnosis.json
opensrp-giz-malawi/src/main/assets/json.form/opd_laboratory.json
opensrp-giz-malawi/src/main/assets/rule/opd/opd_laboratory_relevance_rules.yml
opensrp-giz-malawi/src/main/assets/vaccines.json
opensrp-giz-malawi/src/main/java/org/smartregister/giz/fragment/DailyTalliesFragment.java
opensrp-giz-malawi/src/main/java/org/smartregister/giz/repository/GizMalawiRepository.java
opensrp-giz-malawi/src/main/java/org/smartregister/giz/task/FetchUneditedMonthlyTalliesTask.java
opensrp-giz-malawi/src/main/res/layout/report_expandable_list_view.xml
opensrp-giz-malawi/src/main/res/values/strings.xml
opensrp-giz-malawi/src/test/java/org/smartregister/giz/activity/ReportSummaryActivityTest.java
opensrp-giz-malawi/src/test/java/org/smartregister/giz/fragment/DailyTalliesFragmentTest.java
opensrp-giz-malawi/src/test/java/org/smartregister/giz/task/FetchUneditedMonthlyTalliesTaskTest.java

Recent fixes

---

build.gradle
opensrp-giz-malawi/src/main/assets/json.form/opd_checkin.json
opensrp-giz-malawi/src/test/java/org/smartregister/giz/interactor/LoginInteractorTest.java

add validation on appointment_made_date, on opd_check_in form

---

opensrp-giz-malawi/src/main/assets/json.form/opd_diagnosis.json
opensrp-giz-malawi/src/main/assets/json.form/opd_laboratory.json
opensrp-giz-malawi/src/main/assets/rule/opd/opd_laboratory_relevance_rules.yml

Add malaria microscopy result

---

opensrp-giz-malawi/build.gradle
opensrp-giz-malawi/src/main/assets/json.form/opd_laboratory.json
opensrp-giz-malawi/src/main/assets/rule/opd/opd_laboratory_relevance_rules.yml

Lab form amendments

---

opensrp-giz-malawi/build.gradle
opensrp-giz-malawi/src/main/assets/ec_client_fields.json

477 assign opensrpid to caregiver

---

opensrp-giz-malawi/build.gradle
opensrp-giz-malawi/src/main/assets/ec_client_fields.json
opensrp-giz-malawi/src/main/assets/json.form/adverse_event.json
opensrp-giz-malawi/src/main/java/org/smartregister/giz/activity/ChildDetailTabbedActivity.java
opensrp-giz-malawi/src/test/java/org/smartregister/giz/activity/ChildDetailTabbedActivityTest.java

Reporting fixes

---

opensrp-giz-malawi/build.gradle
opensrp-giz-malawi/src/main/assets/config/indicator-definitions.yml
opensrp-giz-malawi/src/main/java/org/smartregister/giz/repository/GizMalawiRepository.java
opensrp-giz-malawi/src/test/java/org/smartregister/giz/util/GizUtilsTest.java

Fix "`ME_ART_Status_First_Visit_Not_On_ART`" query not to show count when HIV test was not selected.

Fix indicator queries

---

opensrp-giz-malawi/build.gradle

Addresses https://github.com/opensrp/support/issues/263

Update Preview URL

---

opensrp-giz-malawi/build.gradle
opensrp-giz-malawi/src/main/java/org/smartregister/giz/application/GizMalawiApplication.java
opensrp-giz-malawi/src/main/java/org/smartregister/giz/util/GizConstants.java

Addresses https://github.com/opensrp/support/issues/249 and https://github.com/opensrp/support/issues/263

v0.4.5 Malawi: URL Change
